In [1]:
%load_ext autoreload
%autoreload 2

import sys, os, ebf
import numpy as np, pandas as pd

import warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")


%matplotlib inline
from matplotlib import pyplot as plt
from matplotlib.pyplot import NullFormatter
import matplotlib
from matplotlib.colors import LogNorm
font = {'family' : 'normal',
        'weight' : 'bold',
        'size'   : 30}
matplotlib.rc('font', **font)

import seaborn as sns
rc={'font.size': 16, 'axes.labelsize': 16, 'legend.fontsize': 12,
    'axes.titlesize': 18, 'xtick.labelsize': 12, 'ytick.labelsize': 12}
sns.set(font="serif",style="white",rc=rc)

In [5]:
import dynesty

In [2]:
folder = '/home/andy/Documents/Research/SF/SFdata/Galaxia_data/'
iso_folder = '/home/andy/Documents/Research/SF/SFdata/'

In [3]:
sys.path.append('/home/andy/Documents/Research/SF/GitRepo/seestar/')
import StatisticalModels as sm

# Running selection function

In [4]:
sys.path.append('/home/andy/Documents/Research/SF/GitRepo/seestar/')
import SelectionGrid, IsochroneScaling, StatisticalModels, SFInstanceClasses

## Generate selection function from scratch

We have prebuilt the 3 component GMM selection functions so only use gen_obsSF() if you wish to rebuild (takes about 20' on 3 cores).

gen_intSF() takes less than a minute so this is fine.

In [6]:
survey = pd.read_csv(folder + '/Galaxia_sf_survey.csv')
survey['Colour'] = survey.Japp-survey.Kapp

pointings = pd.read_csv(folder + '/Galaxia_sf_fieldinfo.csv')
pointings = pointings[['fieldID', 'glon', 'glat', 'halfangle','Magmin', 'Magmax', 'Colmin', 'Colmax']]
pointings.rename({'glon':'phi', 'glat':'theta'})

def get_spectro(field):
    
    field_data = survey[survey.fieldID==field]
    field_data = np.array(field_data[['Happ', 'Colour']])
    
    return field_data

def get_photo(field):
    
    file_path = folder + '/photometric/'+str(field)+'.csv'
    field_data = pd.read_csv(file_path, usecols=['Japp', 'Happ', 'Kapp'])
    
    field_data['Colour'] = field_data.Japp - field_data.Kapp
    field_data = np.array(field_data[['Happ', 'Colour']])
    
    return field_data

In [7]:
pointings = pointings[1:]

In [ ]:
pointings.Magmin = 'NoLimit'
pointings.Magmax = 'NoLimit'
pointings.Colmin = 'NoLimit'

In [8]:
SF = SelectionGrid.SFGenerator(get_spectro, get_photo, pointings, 
                              spectro_model=('BGM_TNC', None), photo_model=('BGM_TNC', None))

The spectro model description is:('BGM_TNC', None)
The photo model description is:('BGM_TNC', None)


## Generate new selection functions

In [9]:
%%time
SF.gen_obsSF(folder+'/Galaxia_obsSF.pickle')

Creating colour-magnitude field interpolants...
Finished col-mag calculation: 2.0, 1/2, Time: 0.00m, Left: 0.00m('N stars = ', 4501)
Running BGM
(2, '  BIC: ', -43744.74076468005, '   lnP: ', 21922.842711579782)
(3, '  BIC: ', -44502.6685404024, '   lnP: ', 22327.04276406084)
(4, '  BIC: ', -45133.346489727555, '   lnP: ', 22667.617903343293)
(5, '  BIC: ', -45567.47940030124, '   lnP: ', 22909.920523250017)
(6, '  BIC: ', -45765.07091400406, '   lnP: ', 23033.952444721304)
(7, '  BIC: ', -45835.423305170116, '   lnP: ', 23094.36480492421)
(8, '  BIC: ', -45874.0065541511, '   lnP: ', 23138.89259403458)
(9, '  BIC: ', -45865.599291685925, '   lnP: ', 23159.925127421873)
(10, '  BIC: ', -45883.938406915346, '   lnP: ', 23194.33084965646)
(11, '  BIC: ', -45877.92964573579, '   lnP: ', 23216.562633686564)
(12, '  BIC: ', -45769.029847913276, '   lnP: ', 23187.348899395183)
('Best components: ', 10)
('Param shape: ', (10, 6))

('N stars = ', 294)
('Prior boundaries: ', array([[-4.28693339

(False, 'Linear search failed')
(12, '   BIC: ', 2579.9702190008184, '   lnP: ', -1085.3762378762167)
((294, 2), (4501, 2))
[[-5.88803289e-01  9.08632739e-01  7.95746962e-02  8.69870366e-02
  -3.62524089e-01  2.06060606e-01]
 [ 4.29542447e-01 -1.57673764e+00  1.04181512e-01  4.91213078e-02
  -3.13853509e-01  3.08008214e-02]
 [-3.17134560e+00 -1.60886884e+00  6.33234891e-02  6.18496048e-02
   7.22188849e-01  1.28205128e-01]
 [ 3.16788263e-01  1.28641846e-02  6.59280145e-02  4.69086719e-02
   3.01049634e-02  1.25714286e-01]
 [-4.27198299e-01 -6.39772426e-01  7.48634196e-02  9.02794751e-02
   9.54609727e-02  2.10526316e-01]
 [ 5.73178182e-01  8.26572485e-01  9.08595670e-02  5.43808590e-02
  -2.73590880e-02  5.06155951e-02]
 [-1.72070323e+00 -1.28804158e+00  5.48167325e-02  8.46247685e-02
  -4.42284524e-01  1.44578313e-01]
 [-1.84112472e+00 -2.04469029e-01  2.95219833e-03  1.43594917e-01
  -3.06974111e-01  2.50000000e-01]
 [-7.57430145e-01 -1.71284645e+00  3.75105957e-02  4.53002487e-02
  

(False, 'Linear search failed')
(10, '   BIC: ', 2302.981813468927, '   lnP: ', -980.3774324947776)
((300, 2), (4365, 2))
[[-3.17597477 -1.39549125  0.07958146  0.01472636 -0.19498392  0.10416667]
 [ 0.45523181  0.68043028  0.09301003  0.12903918  0.33941801  0.06423358]
 [-0.25345664 -1.7081829   0.0821825   0.04182761 -0.16349884  0.05      ]
 [-0.53907201 -0.44802984  0.08805028  0.0585557  -0.10813798  0.2195122 ]
 [-1.71453537  0.63577591  0.07653031  0.1388709  -0.19952129  0.17073171]
 [-3.12845493 -0.0248556   0.12327603  0.08597649  0.51283959  0.21212121]
 [ 0.66103344 -1.42966861  0.05926437  0.09211814 -0.05924013  0.03019744]
 [-1.37086586 -1.52557586  0.10066512  0.12242548  0.14221267  0.11464968]
 [-2.23070818 -0.69100482  0.07401771  0.03385509  0.21677261  0.21428571]
 [-0.54579246  0.71772946  0.06058182  0.10373472  0.01502979  0.19642857]
 [ 0.68264213 -0.43846036  0.06135147  0.06402968  0.18896061  0.05691057]]
(False, 'Linear search failed')
(11, '   BIC: ', 235

In [30]:
# Likelihood, Prior and Posterior functions
def calc_nlnP_grad_pilogit_NIW(params, Xsf, NIWprior, df_params, stdout=False):

    # Parameters - transform to means, covariances and weights
    params = np.reshape(params, (-1,6))
    # means
    params[:,2:4] = np.abs(params[:,2:4])
    df_idx = np.repeat(np.arange(df_params.shape[0]), params.shape[0])
    sf_idx = np.tile(np.arange(params.shape[0]), df_params.shape[0])
    # covariances
    e_alpha = np.exp(-params[...,4])
    p = 0.999/(1+e_alpha)
    corr = np.sqrt(params[...,2]*params[...,3])*(2*p - 1)
    S_sf = np.moveaxis(np.array([[params[...,2], corr], [corr, params[...,3]]]), -1, 0)
    Sinv_sf, Sdet_sf = StatisticalModels.quick_invdet(S_sf)
    delta_sf = Xsf[:,np.newaxis,:]-params[:,:2][np.newaxis,:,:]
    Sinv_sf_delta = np.sum(Sinv_sf[np.newaxis,...]*delta_sf[...,np.newaxis], axis=2)
    #weights
    # Logit correction of params[:,5] - [-inf, inf] --> [0, rt(det(2.pi.S))]
    e_alpha_pi = np.exp(-params[...,5])
    p_pi = 1./(1+e_alpha_pi)
    pi = 2*np.pi*np.sqrt(Sdet_sf) * p_pi


    # Likelihood
    corr = np.sqrt(df_params[...,2]*df_params[...,3])*df_params[...,4]
    S_df = np.moveaxis(np.array([[df_params[...,2], corr], [corr, df_params[...,3]]]), -1, 0)

    Sinv_sum, Sdet_sum = StatisticalModels.quick_invdet(S_sf[sf_idx]+S_df[df_idx])
    Sinv_sum_delta = np.sum(Sinv_sum*(df_params[:,:2][df_idx] - params[:,:2][sf_idx])[...,np.newaxis], axis=1)

    # Star iteration term
    # (Nstar x Ncomponent_sf)
    m_ij = StatisticalModels.Gaussian_i(delta_sf, Sinv_sf, Sdet_sf)
    m_i = np.sum(pi*m_ij, axis=1)

    # Integral Term
    delta_mumu = params[:,:2][sf_idx] - df_params[:,:2][df_idx]
    I_jl = StatisticalModels.Gaussian_int(delta_mumu, Sinv_sum, Sdet_sum)  * pi[sf_idx] * df_params[:,5][df_idx]
    I = np.sum(I_jl)

    # Prior
    m0, l0, Psi0, nu0 = NIWprior
    delta_mumu0 = params[:,:2]-m0[np.newaxis,:]
    Prior0 = (-(nu0+4.)/2.) * np.log(Sdet_sf)
    Priormu = (-l0/2.) * np.sum(delta_mumu0 * np.sum(Sinv_sf * delta_mumu0[...,np.newaxis], axis=1), axis=1)
    PriorS = (-1/2.) * np.trace(np.matmul(Psi0[np.newaxis,...], Sinv_sf), axis1=-2, axis2=-1)
    Prior = np.sum(Prior0 + Priormu + PriorS)


    return  ( np.sum(np.log(m_i)) - np.sum(I) + Prior)

In [11]:
from dynesty import DynamicNestedSampler

In [16]:
def prior_transform(params):
    
    components = params.reshape(-1, 6)
    components[:,2:4] = (components[:,2:4]+1.)*0.5
    
    components = np.log(components/(1-components))
    
    return components.flatten()

In [17]:
instsf = SF.obsSF[2.0].SF_model
instdf = SF.obsSF[2.0].DF_model
params_df = instsf.params_df

In [18]:
Xsf = np.vstack((instsf.x_s, instsf.y_s)).T

In [19]:
prior_params = StatisticalModels.NIW_prior_params(instsf.prior_sfBounds)

In [31]:
dyn_sampler = DynamicNestedSampler(calc_nlnP_grad_pilogit_NIW, prior_transform, 12,
                     logl_args=(Xsf, prior_params, instsf.params_df), logl_kwargs={'stdout':True})

In [ ]:
dyn_sampler.run_nested()

/home/andy/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:51: RuntimeWarning: divide by zero encountered in log
iter: 2390 | batch: 0 | bound: 61 | nc: 250 | ncall: 46663 | eff(%):  5.068 | loglstar:   -inf < -1037.254 <    inf | logz: -1045.788 +/-  0.037 | dlogz: 103.379 >  0.010            

In [22]:
DynamicNestedSampler?

In [ ]:
dsampler = DynamicNestedSampler(loglike, ptform, ndim, bound='single')